name: create doon db

on:
  push:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  test:
    rans-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --statistics
      - name: Create db
        run: |
          yes | python main.py
      - name: save as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: doonroom_db
          path: ./doonroom.db
    # - name: Test with pytest
    #   run: |
    #     pytest -vv
