name: DB scheduled release

on:
  schedule:
    - cron: "0 15 1 * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          cache: pip
          cache-dependency-path: setup.cfg
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install .[dev]
      - name: Create DB
        run: |
          yes | ddb
      - name: Create dump
        run: |
          echo .dump | sqlite3 doonroom.db | python sqlite_mysql_conv.py > doonroom_my.sql
      - name: Get date
        run: |
          echo "DATE=$(date +%y%m%d)" >> $GITHUB_ENV
      - name: Rename artifacts
        run: |
          mv doonroom.db doonroom_${{ env.DATE }}.db
          mv doonroom_my.sql doonroom_my_${{ env.DATE }}.sql
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "doonroom_*.db,doonroom_my_*.sql"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: month${{ env.DATE }}
          artifactErrorsFailBuild: true
